# HTTPS for tar1090-combo — required for browser GPS geolocation
server.modules += ("mod_openssl")

$SERVER["socket"] == ":8506" {
    ssl.engine = "enable"
    ssl.pemfile = "/etc/lighttpd/certs/server.pem"

    url.redirect += (
      "^$" => "/"
    )

    alias.url += (
      "/data/" => "/run/combine1090/",
      "/chunks/" => "/run/tar1090-combo/",
      "/globe_history/" => "/var/globe_history/",
      "/skyaware978/" => "/run/dump978/",
      "/aircraft_sil/" => "/usr/local/share/tar1090/aircraft_sil/",
      "/osm_tiles_offline/" => "/usr/local/share/osm_tiles_offline/",
      "/" => "/usr/local/share/tar1090/html-combo/"
    )

    $HTTP["url"] =~ "^/chunks/chunk_.*gz$" {
        setenv.add-response-header += (
            "Access-Control-Allow-Origin" => "*",
            "Cache-Control" => "public, max-age=1209600",
            "Content-Encoding" => "gzip",
            "Content-Type" => "application/json",
        )
    }
    $HTTP["url"] =~ "^/chunks/current_.*gz$" {
        setenv.add-response-header += (
            "Access-Control-Allow-Origin" => "*",
            "Cache-Control" => "no-cache",
            "Content-Encoding" => "gzip",
            "Content-Type" => "application/json",
        )
    }
    $HTTP["url"] =~ "^/chunks/978\.json$" {
        setenv.add-response-header += (
            "Cache-Control" => "no-cache",
        )
    }
    $HTTP["url"] =~ "^/data/aircraft\.json$" {
        setenv.add-response-header += (
            "Cache-Control" => "no-cache",
        )
    }
    $HTTP["url"] =~ "^/config.js$" {
        setenv.add-response-header += (
            "Cache-Control" => "no-cache",
        )
    }
    $HTTP["url"] =~ "^/(?!config)[^/]*\.js$" {
        setenv.add-response-header += (
            "Cache-Control" => "public, max-age=1209600",
        )
    }
    $HTTP["url"] =~ "^/db-.*\.js$" {
        setenv.add-response-header += (
            "Cache-Control" => "public, max-age=1209600",
            "Content-Encoding" => "gzip",
        )
    }
    $HTTP["url"] =~ "^/libs/.*$" {
        setenv.add-response-header += (
            "Cache-Control" => "public, max-age=1209600",
        )
    }
    $HTTP["url"] =~ "^/images" {
        setenv.add-response-header += (
            "Cache-Control" => "public, max-age=1209600",
        )
    }
    $HTTP["url"] =~ "^/flags" {
        setenv.add-response-header += (
            "Cache-Control" => "public, max-age=1209600",
        )
    }
    $HTTP["url"] =~ "^/aircraft_sil" {
        setenv.add-response-header += (
            "Cache-Control" => "public, max-age=1209600",
        )
    }
    $HTTP["url"] =~ "^/style.css$" {
        setenv.add-response-header += (
            "Cache-Control" => "public, max-age=1209600",
        )
    }
}
